/* 게시판이미지 */
CREATE TABLE IMAGE_RELATION (
	ID_BOARD VARCHAR2(2000), /* 게시물번호 */
	ID_IMAGE VARCHAR2(2000) /* 이미지번호 */
);

/* 취미관계 */
CREATE TABLE HOBBY_RELATION (
	ID_USER VARCHAR2(100), /* EmailID */
	ID_HOBBY VARCHAR2(2000) /* 취미번호 */
);

/* 게시판이미지 정보 */
CREATE TABLE IMAGE (
	ID_IMAGE VARCHAR2(2000) NOT NULL, /* 이미지번호 */
	IMAGE VARCHAR2(2000) /* 이미지 */
);

CREATE UNIQUE INDEX PK_IMAGE
	ON IMAGE (
		ID_IMAGE ASC
	);

ALTER TABLE IMAGE
	ADD
		CONSTRAINT PK_IMAGE
		PRIMARY KEY (
			ID_IMAGE
		);

/* 회원정보 */
CREATE TABLE USERS (
	ID_USER VARCHAR2(100) NOT NULL, /* EmailID */
	PASSWORD_USER VARCHAR2(20), /* 비밀번호 */
	NAME_USER VARCHAR2(20), /* 회원이름 */
	ID_LOCATION VARCHAR2(100) /* 지역번호 */
);

CREATE UNIQUE INDEX PK_USERS
	ON USERS (
		ID_USER ASC
	);

ALTER TABLE USERS
	ADD
		CONSTRAINT PK_USERS
		PRIMARY KEY (
			ID_USER
		);

/* 게시판 */
CREATE TABLE BOARD (
	ID_BOARD VARCHAR2(2000) NOT NULL, /* 게시물번호 */
	TITLE_BOARD VARCHAR2(100), /* 제목 */
	DESCRIPT_BOARD VARCHAR2(2000), /* 내용 */
	LIKE_BOARD VARCHAR2(100), /* 좋아요 */
	SCRAP_BOARD VARCHAR2(100), /* 스크랩 */
	ID_USER VARCHAR2(100) /* EmailID */
);

CREATE UNIQUE INDEX PK_BOARD
	ON BOARD (
		ID_BOARD ASC
	);

ALTER TABLE BOARD
	ADD
		CONSTRAINT PK_BOARD
		PRIMARY KEY (
			ID_BOARD
		);

/* 회원권한 */
CREATE TABLE AUTH_RELATION (
	ID_USER VARCHAR2(100) NOT NULL, /* EmailID */
	ID_AUTHORITY VARCHAR2(100) /* 권한번호 */
);

/* 권한정보 */
CREATE TABLE AUTH (
	ID_AUTHORITY VARCHAR2(100) NOT NULL, /* 권한번호 */
	AUTHORITY VARCHAR2(2000) /* 권한명 */
);

CREATE UNIQUE INDEX PK_AUTH
	ON AUTH (
		ID_AUTHORITY ASC
	);

ALTER TABLE AUTH
	ADD
		CONSTRAINT PK_AUTH
		PRIMARY KEY (
			ID_AUTHORITY
		);

/* 취미정보 */
CREATE TABLE HOBBY (
	ID_HOBBY VARCHAR2(2000) NOT NULL, /* 취미번호 */
	HOBBY VARCHAR2(2000) /* 취미 */
);

CREATE UNIQUE INDEX PK_HOBBY
	ON HOBBY (
		ID_HOBBY ASC
	);

ALTER TABLE HOBBY
	ADD
		CONSTRAINT PK_HOBBY
		PRIMARY KEY (
			ID_HOBBY
		);

/* 지역 */
CREATE TABLE LOCATION (
	ID_LOCATION VARCHAR2(100) NOT NULL, /* 지역번호 */
	LOCATION VARCHAR2(100) /* 지역명 */
);

CREATE UNIQUE INDEX PK_LOCATION
	ON LOCATION (
		ID_LOCATION ASC
	);

ALTER TABLE LOCATION
	ADD
		CONSTRAINT PK_LOCATION
		PRIMARY KEY (
			ID_LOCATION
		);

/* 스크랩 관계 */
CREATE TABLE SCRAP_RELATION (
	ID_USER VARCHAR2(100), /* EmailID */
	ID_BOARD VARCHAR2(2000) /* 게시물번호 */
);

ALTER TABLE IMAGE_RELATION
	ADD
		CONSTRAINT FK_BOARD_TO_IMAGE_RELATION
		FOREIGN KEY (
			ID_BOARD
		)
		REFERENCES BOARD (
			ID_BOARD
		);

ALTER TABLE IMAGE_RELATION
	ADD
		CONSTRAINT FK_IMAGE_TO_IMAGE_RELATION
		FOREIGN KEY (
			ID_IMAGE
		)
		REFERENCES IMAGE (
			ID_IMAGE
		);

ALTER TABLE HOBBY_RELATION
	ADD
		CONSTRAINT FK_USERS_TO_HOBBY_RELATION
		FOREIGN KEY (
			ID_USER
		)
		REFERENCES USERS (
			ID_USER
		);

ALTER TABLE HOBBY_RELATION
	ADD
		CONSTRAINT FK_HOBBY_TO_HOBBY_RELATION
		FOREIGN KEY (
			ID_HOBBY
		)
		REFERENCES HOBBY (
			ID_HOBBY
		);

ALTER TABLE USERS
	ADD
		CONSTRAINT FK_LOCATION_TO_USERS
		FOREIGN KEY (
			ID_LOCATION
		)
		REFERENCES LOCATION (
			ID_LOCATION
		);

ALTER TABLE BOARD
	ADD
		CONSTRAINT FK_USERS_TO_BOARD
		FOREIGN KEY (
			ID_USER
		)
		REFERENCES USERS (
			ID_USER
		);

ALTER TABLE AUTH_RELATION
	ADD
		CONSTRAINT FK_USERS_TO_AUTH_RELATION
		FOREIGN KEY (
			ID_USER
		)
		REFERENCES USERS (
			ID_USER
		);

ALTER TABLE AUTH_RELATION
	ADD
		CONSTRAINT FK_AUTH_TO_AUTH_RELATION
		FOREIGN KEY (
			ID_AUTHORITY
		)
		REFERENCES AUTH (
			ID_AUTHORITY
		);

ALTER TABLE SCRAP_RELATION
	ADD
		CONSTRAINT FK_USERS_TO_SCRAP_RELATION
		FOREIGN KEY (
			ID_USER
		)
		REFERENCES USERS (
			ID_USER
		);

ALTER TABLE SCRAP_RELATION
	ADD
		CONSTRAINT FK_BOARD_TO_SCRAP_RELATION
		FOREIGN KEY (
			ID_BOARD
		)
		REFERENCES BOARD (
			ID_BOARD
		);